#pragma once

#include <array>
#include <unistd.h>
#include "glm/glm.hpp"
#include "glm/gtc/matrix_transform.hpp"

#include "vulkanFrame.h"

#define CHESSBOARD_LINE_WIDTH 1

#define CHESSBOARD_RECT_SIZE 50

//棋盘内一行或一列的小矩形数量, 如果要算窗口大小，应该加2
#define CHESSBOARD_RECT_COUNT 16
// #define CHESSBOARD_RECT_COUNT 10
//四个大矩形中，每个矩形所占的行数
#define CHESSBOARD_BING_GRID_DENSITY 4
// #define CHESSBOARD_BING_GRID_DENSITY 3

#define MAX_CHESSBOARD_LINE (CHESSBOARD_RECT_COUNT + 1)
//通常用于数组遍历
#define CHESSBOARD_ROW CHESSBOARD_RECT_COUNT
#define CHESSBOARD_COLUMN CHESSBOARD_ROW

//黑色背景...一般情况下无需修改
#define CHESSBOARD_BACKGROUND_SIZE(WINDOW_WIDTH)(WINDOW_WIDTH - 2 * CHESSBOARD_RECT_SIZE)

#define CHESSBOARD_BOUNDARY_CENTER_RECT_COUNT (CHESSBOARD_RECT_COUNT - CHESSBOARD_BING_GRID_DENSITY * 2)
//该宏作用非常小，修改价值低
#define CHESSBOARD_BIG_GRID_COUNT 4
#define CHESSBOARD_BIG_RECT_SIZE (CHESSBOARD_RECT_SIZE * CHESSBOARD_BING_GRID_DENSITY + CHESSBOARD_LINE_WIDTH * CHESSBOARD_BING_GRID_DENSITY - 1)

#define ROW_COLUMN_TO_INDEX(ROW_INDEX, COLUMN_INDEX, COLUMN)((ROW_INDEX) * (COLUMN) + (COLUMN_INDEX))

//最好不要修改
#define WU_COUNTRY_INDEX 0
#define WEI_COUNTRY_INDEX 1
#define SHU_COUNTRY_INDEX 2
#define HAN_COUNTRY_INDEX 3
#define INVALID_COUNTRY_INDEX -1
//该宏应该减少使用,尽量使用Game类中的国家总数
#define MAX_COUNTRY_INDEX 4

//联盟相关宏, 一般情况下需要修改
#define ALLIANCE_POINT_FONT_WIDTH 25
#define ALLIANCE_POINT_FONT_HEIGHT ALLIANCE_POINT_FONT_WIDTH
#define ALLIANCE_POINT_FONT_INDEX_WU 0
#define ALLIANCE_POINT_FONT_INDEX_WEI 1
#define ALLIANCE_POINT_FONT_INDEX_SHU 2
#define ALLIANCE_POINT_WIDTH 15
#define ALLIANCE_POINT_HEIGHT ALLIANCE_POINT_WIDTH

//字体宏一般情况下需要修改
//字体大小不一定要和棋子大小一样
#define FONT_WIDTH 40
#define FONT_HEIGHT FONT_WIDTH

#define FONT_INDEX_MA 7
#define FONT_INDEX_PAO 5
#define FONT_INDEX_CHE 6
#define FONT_INDEX_SHI 9
#define FONT_INDEX_BING 4
#define FONT_INDEX_XIANG 8

#define FONT_INDEX_WU 0
#define FONT_INDEX_SHU 1
#define FONT_INDEX_WEI 2
#define FONT_INDEX_HAN 3

#define CHESS_WIDTH 20
#define CHESS_HEIGHT CHESS_WIDTH

//仅修改数量不够, 还需设置它们的位置
#define SHI_CHESS_COUNT 2
#define MA_CHESS_COUNT 2
#define PAO_CHESS_COUNT 2
#define CHE_CHESS_COUNT 2
#define BING_CHESS_COUNT 5
#define JIANG_CHESS_COUNT 1
#define XIANG_CHESS_COUNT 2
#define HAN_CHE_CHESS_COUNT 3
#define HAN_PAO_CHESS_COUNT 1
//一般情况不需要修改。添加新棋的话，应该从最后加索引, 也就是目前的兵
#define JIANG_CHESS_INDEX 0
#define MA_CHESS_INDEX (JIANG_CHESS_INDEX + JIANG_CHESS_COUNT)
#define PAO_CHESS_INDEX (MA_CHESS_INDEX + MA_CHESS_COUNT)
#define CHE_CHESS_INDEX (PAO_CHESS_INDEX + PAO_CHESS_COUNT)
#define SHI_CHESS_INDEX (CHE_CHESS_INDEX + CHE_CHESS_COUNT)
#define XIANG_CHESS_INDEX (SHI_CHESS_INDEX + SHI_CHESS_COUNT)
#define BING_CHESS_INDEX (XIANG_CHESS_INDEX + XIANG_CHESS_COUNT)

#define HAN_PAO_CHESS_INDEX 1
#define HAN_CHE_CHESS_INDEX (HAN_PAO_CHESS_INDEX + HAN_PAO_CHESS_COUNT)

#define COUNTRY_CHESS_COUNT (BING_CHESS_COUNT + PAO_CHESS_COUNT + CHE_CHESS_COUNT + MA_CHESS_COUNT + XIANG_CHESS_COUNT + SHI_CHESS_COUNT + JIANG_CHESS_COUNT)
//一般情况不需要修改
#define DRAW_CHESS_COUNT (COUNTRY_CHESS_COUNT * 3)
//每个国家需要绘制4个矩形
#define CHESSBOARD_PALACE_COUNT (MAX_COUNTRY_INDEX * 4)

//vulkan专用，无特殊情况不要修改
//如果val比alignment小，则返回alignment，否则如果val大于alignment但小于alignment*2则返回alignment*2以此类推
#define ALIGN(val, alignment)((val + alignment - 1) & ~(alignment - 1))

#define ROW_COLUMN_TO_INDEX(ROW_INDEX, COLUMN_INDEX, COLUMN)((ROW_INDEX) * (COLUMN) + (COLUMN_INDEX))

#define CHESS_COLUMN_TO_X(COLUMN)((COLUMN + 1) * (CHESSBOARD_RECT_SIZE) + (COLUMN + 1) * CHESSBOARD_LINE_WIDTH)
#define CHESS_ROW_TO_Y(ROW)(CHESS_COLUMN_TO_X(ROW))